name: Ruby CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rubocop:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  test:
    name: Test on Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # automatically runs bundle install and caches gems

    - name: Compile Native C-Extension
      run: bundle exec rake compile

    - name: Run Test Suite
      run: bundle exec rake test
